version: '3'
services: 
  nginx:
    image: nginx:1
    ports:
      - "8080:80"
    volumes:
      - './public/:/www/public/:rw'
      - './.docker.develop/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: .docker.develop/php/Dockerfile
    volumes:
      - '.:/www/:rw'
      - './.docker.develop/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro'
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'percona/percona-server:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - '8036:3306'
    volumes:
      - /var/log/mysql
      - /var/lib/mysql
    command:
      - '--user=mysql'
  redis:
    image: redis:4-alpine
    ports:
      - '8079:6379'
    volumes:
     - /data
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
